window.itemsBackwall =[
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | HTU | CHAROLAHTU",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_HTU_CHAROLAHTU",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "HTU",
      "CHAROLAHTU"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER HTU CHAROLAHTU",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER-HTU_CHAROLAHTU.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER-ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | LM | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_LM_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "LM",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 LM MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_LM_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | LM | MLB25 | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_LM_MLB25_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "LM",
      "MLB25",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 LM MLB25 HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_LM_MLB25-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | LM | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_LM_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "LM",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 LM MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_LM_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | LM | MLB25 | HTU | ZYN | CHAROLAZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_LM_MLB25_HTU_ZYN_CHAROLAZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "LM",
      "MLB25",
      "HTU",
      "ZYN",
      "CHAROLAZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 LM MLB25 HTU ZYN CHAROLAZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_LM_MLB25-HTU_ZYN_CHAROLAZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | LM | MLB25 | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_LM_MLB25_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "LM",
      "MLB25",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 LM MLB25 ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_LM_MLB25-ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | 25 | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_25_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "25",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS 25 MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS+25_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | MLB25 | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_MLB25_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "MLB25",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM MLB25 HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM_MLB25-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | MLB25 | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_MLB25_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "MLB25",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM MLB25 ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM_MLB25-ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | LM | MLB25 | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_LM_MLB25_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "LM",
      "MLB25",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS LM MLB25 ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_LM_MLB25-ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | FAROS | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_FAROS_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "FAROS",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS FAROS MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_FAROS_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25 | CHAROLAHTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25_CHAROLAHTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25",
      "CHAROLAHTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25 CHAROLAHTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-CHAROLAHTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25 | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25 HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25 | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25 ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | LM | MLB25 | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_LM_MLB25_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "LM",
      "MLB25",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS LM MLB25 ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_LM_MLB25-ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | MLB25",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_MLB25",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "MLB25"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS MLB25",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_MLB25-.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | MLB25 | HTU | CHAROLAHTU | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_MLB25_HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "MLB25",
      "HTU",
      "CHAROLAHTU",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS MLB25 HTU CHAROLAHTU ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_MLB25-HTU_CHAROLAHTU_ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | MLB25 | HTU | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_MLB25_HTU_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "MLB25",
      "HTU",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS MLB25 HTU ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_MLB25-HTU_ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | MLB25 | ZYN",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_MLB25_ZYN",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "MLB25",
      "ZYN"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS MLB25 ZYN",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_MLB25-ZYN.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  },
  {
    "title": "BACKWALL | 4 CHAROLAS | HEADER | Q425 | OXXO | BWLL | 5 | CHAROLAS | MLB25 | ZYN | CHAROLAZYN2025",
    "code": "OXXO_BACKWALL_4CHAROLAS_HEADER_Q425_OXXO_BWLL_5_CHAROLAS_MLB25_ZYN_CHAROLAZYN2025",
    "family": [
      "BACKWALL",
      "4 CHAROLAS",
      "HEADER",
      "Q425",
      "OXXO",
      "BWLL",
      "5",
      "CHAROLAS",
      "MLB25",
      "ZYN",
      "CHAROLAZYN2025"
    ],
    "tags": "BACKWALL 4 CHAROLAS HEADER Q425 OXXO BWLL 5 CHAROLAS MLB25 ZYN CHAROLAZYN2025",
    "img": "Q425_OXXO_BWLL_5 CHAROLAS_HEADER_MLB25-ZYN_CHAROLAZYN2025.jpg",
    "categoria": "backwall",
    "cadena": "oxxo"
  }
]
